### ISSUE TITLE
Automate Webserver and Database Server Management with Ansible

### ISSUE THREAD

**Issue by Shafiya-Heena** [creativecommons/ansible-dev#4]
## Description
The goal of this issue is to automate the management of our webserver and database server using Ansible. This includes the setup, configuration, and ongoing maintenance tasks for both servers to ensure a streamlined and efficient deployment process.

#### Objectives:
Automation of Webserver Setup: Utilize Ansible to automate the setup and configuration of the webserver, ensuring it is optimized for performance and security.
Database Server Management: Apply Ansible scripts to manage the database server, including database creation, user permissions, and backup procedures.
Scalability and Maintenance: Ensure that the Ansible playbook provides scalability options and easy maintenance tasks, such as updates and security patches.

#### Expected Outcome:
A set of Ansible playbooks and roles that automate the deployment and management of the webserver and database server.
Documentation on how to use the Ansible scripts for setup, deployment, and maintenance.
A scalable and secure setup that can be easily updated and maintained through Ansible

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by Cappybara12** [comment]
Hey @Shafiya-Heena ,

I came across your comment regarding about automating servers with Ansible. It's awesome that you're interested in that aspect! However, just to clear things up, the issues in this repo usually focus on specific technical challenges or bugs rather than the overall project objectives listed in the GSoC description.

Feel free to dive into existing issues or propose new ones related to Ansible automation, though! Your enthusiasm is appreciated, and I look forward to help you out if you need any. I am a gsoc contributor myself would love to get along the project with your insights aswell

**Comment by Cappybara12** [comment]
@Shafiya-Heena I'm really excited about the opportunity to contribute to this issue! The objectives and expected outcomes align perfectly with my interests and skills. I would love to take on the challenge of automating the management of our webserver and database server using Ansible.

Looking forward to diving into this and contributing to the project!

**Comment by Shafiya-Heena** [comment]
Thank you @Cappybara12  for expressing your interest in contributing! We truly appreciate your eagerness. Before you begin, we kindly ask that you familiarize yourself with the [Contribution Guidelines — Creative Commons Open Source](https://opensource.creativecommons.org/contributing-code/). 

Currently, the issue has not been marked with the "help wanted" label, indicating that it's not ready for contributions just yet. We'll make sure to update it as soon as it's prepared for work.

**Comment by Cappybara12** [comment]
Thank you for mentioning this! . I am already familiarized with the guidelines just wanted to show my interest , am active on slack channel of CC as well
