### ISSUE TITLE
Utilize organization default community health files

### ISSUE THREAD

**Issue by nox1134** [creativecommons/ansible-dev#6]
## Description
Remove duplicate files from the repository to ensure alignment with organizational defaults as outlined in GitHub Repo Guidelines.

Related to:
(https://github.com/creativecommons/.github/issues/38)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Abhishek14104** [comment]
Hey, @nox1134 welcome to the community thanks for your interest in contributing to the project. However, the problem has not yet been authorised. A project maintainer will assess the problem and determine whether to approve a pull request after some time.
A PR can be filed once the issue has been authorised by the project maintainer and the status "awaiting triage label" has been removed.
To learn more, review the Contribution Guidelines.
